apiVersion: v1
kind: Service
metadata:
  name: minecraft-service
spec:
  type: LoadBalancer
  selector:
    app: minecraft # This MUST match the label in your deployment
  ports:
    - name: minecraft 
      protocol: TCP
      port: 25565
      targetPort: 25565
    - name: metrics
      port: 2400
      targetPort: 2400    
